version: '3.4'

services:
  sf.iy.insurancepolicy.demoapi:
    image: ${DOCKER_REGISTRY-}sfiyinsurancepolicydemoapi
    build:
      context: .
      dockerfile: SF.IP.InsurancePolicy.DemoAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https:http://+:80
      - QueueHost=sf-rabbitmq
      - QueueUserName=guest
      - QueuePassword=guest
      - QueuePort=5672  
    ports:
      - 8000:80
      - 8003:443
    restart: on-failure   
    depends_on:
      - sf-rabbitmq   

  sf-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: sf-rabbitmq
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672